format = """
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
truncation_length=0
home_symbol="/home/korin"
truncate_to_repo=false
style="bold white"


[git_branch]
format = "($branch)"
style = "bold green"

[git_status]
format="($all_status)"
style = "bold red"

[character]
success_symbol = "[%](bold green)"
error_symbol = "[%](bold red)"
vicmd_symbol = "[%](bold blue)"
