set -g status-position top

set -g status-right "%H:%M | %h-%d | [#(acpi | grep -o '[^ ]*%%')] "

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -n C-k split-window -h
bind -n C-l split-window -v

bind -n C-p select-pane -t:.+

bind -n C-S-Up copy-mode -e \; send-keys -X scroll-up
bind -n C-S-Down copy-mode -e \; send-keys -X scroll-down
