set -g status-position top

set -g status-right "%H:%M | %h-%d | [#(acpi | grep -o '[^ ]*%%')] "

set -g xterm-keys on
set -g extended-keys on

unbind C-b
set -g prefix C-a
#bind C-a send-prefix

bind -n C-k split-window -h
bind -n C-j split-window -v


bind -n M-t resize-pane -L 5
bind -n M-y resize-pane -R 5
bind -n C-M-t resize-pane -U 5
bind -n C-M-y resize-pane -D 5

bind -n C-p select-pane -t:.+

bind -n M-Enter copy-mode
